version: '3.8'

services:
  postgres_storing:
    image: postgres:15
    container_name: postgres_storing
    environment:
      POSTGRES_DB: filestoring
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_storing:/var/lib/postgresql/data

  postgres_analysis:
    image: postgres:15
    container_name: postgres_analysis
    environment:
      POSTGRES_DB: fileanalysis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata_analysis:/var/lib/postgresql/data

  file-storing-service:
    build:
      context: ./file-storing-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres_storing
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_storing:5432/filestoring
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  file-analysis-service:
    build:
      context: ./file-analysis-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres_analysis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_analysis:5432/fileanalysis
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - file-storing-service
      - file-analysis-service

volumes:
  pgdata_storing:
  pgdata_analysis:
